### ISSUE TITLE
Remove Yarn binary from repo

### ISSUE THREAD

**Issue by jlvandenhout** [iota-community/iota-wiki#585]
**Is your feature request related to a problem? Please describe.**
In the early modern Yarn releases it was required to check in the binary. This requirement seems to be dropped with the release of [Corepack together with newer Node.js versions](https://yarnpkg.com/getting-started/install).

**Describe the solution you'd like**
We can remove the Yarn binary from the repo and update our docs to reflect the new way of installing and using modern Yarn with Node.js.

**TODO**
- [x] Remove the Yarn binary.
- [x] Update the README how to install Node.js version and modern Yarn with Corepack.
- [ ] Repeat the above for all documentation repositories.

**Comment by jlvandenhout** [comment]
Closed by #644
